---
sudo: required
language: python
env:
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - python3 -m install molecule yamllint ansible-lint docker
  # - python3 -m pip install required driver (e.g. docker, shade, boto, apache-libcloud)
script:
  - molecule test
