---
- name: git clone Solarized Color Theme for LS_COLORS
  become: true
  become_user: "{{ username }}"
  git:
    depth: "1"
    repo: https://github.com/seebi/dircolors-solarized.git
    dest: "/home/{{ username }}/.config/dircolors-solarized"
    clone: yes
    update: yes
