---
- name: Install dependencies
  become: true
  apt:
    name:
      - git
      - zsh
      - tree
    update_cache: yes
    cache_valid_time: 3600

- name: Check if .oh-my-zsh exists /home/{{ username }}/.oh-my-zsh
  become: true
  become_user: "{{ username }}"
  stat:
    path: "/home/{{ username }}/.oh-my-zsh"
  register: stat_oh_my_zsh_result

- name: Directory .oh-my-zsh exists
  debug:
    msg: "Success, path exists and user can read stats will skip cloning oh-my-zsh"
  when: stat_oh_my_zsh_result.stat.isdir is defined

- name: clone oh-my-zsh for {{ username }}
  become: true
  become_user: "{{ username }}"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ username }}/.oh-my-zsh"
    clone: yes
    update: no
  when: stat_oh_my_zsh_result.stat.isdir is not defined

# - name: set permissions of oh-my-zsh for {{ username }}
#   become: true
#   file:
#     path: "/home/{{ username }}/.oh-my-zsh"
#     owner: "{{ username }}"
#     group: "{{ usergroup }}"
#     mode: "0760"
#     recurse: yes

- name: set default shell for {{ username }}
  become: true
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: write .zshrc for user {{ username }}
  become: true
  become_user: "{{ username }}"
  template:
    src: zshrc.j2
    dest: "/home/{{ username }}/.zshrc"
    mode: "u=rw,go=r"
