---
- name: Install dependencies
  become: true
  register: results
  apt:
    name:
      - neofetch

- name: Create a directory if it does not exist
  become: true
  become_user: "{{ username }}"
  file:
    path: /home/{{ username }}/.config/neofetch
    state: directory
    mode: "0760"

- name: Copy a new neofetch.conf file into to /home/{{ username }}/.config/neofetch/config.conf
  become: true
  become_user: "{{ username }}"
  copy:
    src: neofetch.conf
    dest: "/home/{{ username }}/.config/neofetch/config.conf"
    mode: u=rw,g=r,o=r
