---
# tasks file for ansible-zsh-p10k-role
- import_tasks: debian-zsh.yml
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: debian-powerline10k.yml
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: debian-neofetch.yml
  when: ansible_facts['os_family']|lower == 'debian'
