---
# tasks file for ansible-zsh-p10k-role
- import_tasks: debian-zsh.yml
  when: ansible_facts['os_family'] == 'Debian'

- import_tasks: debian-powerline10k.yml
  when: ansible_facts['os_family'] == 'Debian'

- import_tasks: debian-solarized.yml
  when: ansible_facts['os_family'] == 'Debian'

- import_tasks: debian-neofetch.yml
  when: (ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_version'] >= "18.04")
