---
- name: Converge
  hosts: all
  become: true

  vars:
    username: josh
    usergroup: sudo

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Add the user {{ username }} with a specific uid and a primary group of {{ usergroup }}
      user:
        name: "{{ username }}"
        uid: 1000
        group: "{{ usergroup }}"
        create_home: true
        shell:

  roles:
    - role: ansible-role-zsh-p10k
